module.exports = {
	USER_JOINED: "USER_JOINED",
	MESSAGE_RECIEVED: "MESSAGE_RECIEVED",
	MESSAGE_SENT: "MESSAGE_SENT",
	USER_DISCONNECTED: "USER_DISCONNECTED",
	TYPING: "TYPING",
	LOGOUT: "LOGOUT",
	UNAUTH_USER: "UNAUTH_USER",
	AUTH_USER: "AUTH_USER",
	AUTH_ERROR: "AUTH_ERROR",
	FETCH_MESSAGE: "FETCH_MESSAGE"
};
