module.exports = {
  CLEAR_MISSED_MSG: 'CLEAR_MISSED_MSG',
  CLEAR_NOTICES: 'CLEAR_NOTICES',
  GET_MESSAGES: 'GET_MESSAGES',
  MESSAGE_SENT: 'MESSAGE_SENT',
  LOADING: 'LOADING',
  LOGGED_IN: 'LOGGED_IN',
  LOGIN_ERROR: 'LOGIN_ERROR',
  LOGOUT: 'LOGOUT',
  STOPPED_TYPING: 'STOPPED_TYPING',
  TYPING: 'TYPING',
  SOCKET_EVENTS: [
    'MESSAGE_SENT',
    'STOPPED_TYPING',
    'TYPING',
    'USER_CONNECTED',
    'USER_DISCONNECTED',
  ],
  USER_CONNECTED: 'USER_CONNECTED',
  USER_DISCONNECTED: 'USER_DISCONNECTED',
};

